name: Test transpiler

on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'INSTALL.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'INSTALL.md'
      - 'docs/**'

jobs:
  run:
    strategy:
      matrix:
        include:
          - name: "[Ubuntu] CMake + gcc-12"
            os: ubuntu-22.04
            CC: gcc-12
            CXX: g++-12
            FC: gfortran-12
            OCCA_FORTRAN_ENABLED: 1

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    env:
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
      FC: ${{ matrix.FC }}
      OCCA_CXXFLAGS: -O3
      OCCA_COVERAGE: ${{ matrix.OCCA_COVERAGE }}
      OCCA_FORTRAN_ENABLED: ${{ matrix.OCCA_FORTRAN_ENABLED }}
      FORTRAN_EXAMPLES: ${{ matrix.OCCA_FORTRAN_ENABLED }}

    steps:
    - uses: actions/checkout@v4

    - name: install clang version required for the transpiler
      shell: bash -el {0}
      run: |
        wget https://raw.githubusercontent.com/opencollab/llvm-jenkins.debian.net/master/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 17 all

    - name: CMake configure
      shell: bash -el {0}
      run: |
        cmake -S . -B build \
        -DCMAKE_BUILD_TYPE="RelWithDebInfo" \
        -DCMAKE_INSTALL_PREFIX=install \
        -DCMAKE_C_COMPILER=${CC} \
        -DCMAKE_CXX_COMPILER=${CXX} \
        -DCMAKE_Fortran_COMPILER=${FC} \
        -DOCCA_ENABLE_TESTS=ON \
        -DOCCA_ENABLE_EXAMPLES=ON \
        -DOCCA_ENABLE_FORTRAN=${OCCA_FORTRAN_ENABLED} \
        -DOCCA_CLANG_BASED_TRANSPILER=ON

    - name: CMake build
      run: |
        cmake --build build --parallel 8
